# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mitm_hub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mitm_hub.proto',
  package='mitm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emitm_hub.proto\x12\x04mitm\"\x0e\n\x0cVoidResponse\"\x93\x01\n\x15MitmproxyStartRequest\x12\x0c\n\x04\x62ind\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x1a\n\x12\x63\x61llbackServerAddr\x18\x03 \x01(\t\x12\x1a\n\x12\x63\x61llbackServerPort\x18\x04 \x01(\x05\x12\x10\n\x08upstream\x18\x05 \x01(\t\x12\x14\n\x0cupstreamAuth\x18\x06 \x01(\t\"-\n\x16MitmproxyStartResponse\x12\x13\n\x0bmitmproxyId\x18\x01 \x01(\t\"+\n\x14MitmproxyStopRequest\x12\x13\n\x0bmitmproxyId\x18\x01 \x01(\t\")\n\nMitmHeader\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"s\n\x0bMitmRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12!\n\x07headers\x18\x03 \x03(\x0b\x32\x10.mitm.MitmHeader\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x13\n\x0bmitmproxyId\x18\x05 \x01(\t\"\x8f\x01\n\x0cMitmResponse\x12\"\n\x07request\x18\x01 \x01(\x0b\x32\x11.mitm.MitmRequest\x12!\n\x07headers\x18\x02 \x03(\x0b\x32\x10.mitm.MitmHeader\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x12\n\nstatusCode\x18\x04 \x01(\x05\x12\x13\n\x0bmitmproxyId\x18\x05 \x01(\t2\x94\x01\n\x12MitmProxyHubServer\x12\x44\n\x05start\x12\x1b.mitm.MitmproxyStartRequest\x1a\x1c.mitm.MitmproxyStartResponse\"\x00\x12\x38\n\x04stop\x12\x1a.mitm.MitmproxyStopRequest\x1a\x12.mitm.VoidResponse\"\x00\x32\x8f\x01\n\x18MitmProxyHubClientServer\x12\x37\n\ronMitmRequest\x12\x11.mitm.MitmRequest\x1a\x11.mitm.MitmRequest\"\x00\x12:\n\x0eonMitmResponse\x12\x12.mitm.MitmResponse\x1a\x12.mitm.MitmResponse\"\x00\x62\x06proto3'
)




_VOIDRESPONSE = _descriptor.Descriptor(
  name='VoidResponse',
  full_name='mitm.VoidResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=38,
)


_MITMPROXYSTARTREQUEST = _descriptor.Descriptor(
  name='MitmproxyStartRequest',
  full_name='mitm.MitmproxyStartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bind', full_name='mitm.MitmproxyStartRequest.bind', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='mitm.MitmproxyStartRequest.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callbackServerAddr', full_name='mitm.MitmproxyStartRequest.callbackServerAddr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callbackServerPort', full_name='mitm.MitmproxyStartRequest.callbackServerPort', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upstream', full_name='mitm.MitmproxyStartRequest.upstream', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upstreamAuth', full_name='mitm.MitmproxyStartRequest.upstreamAuth', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=188,
)


_MITMPROXYSTARTRESPONSE = _descriptor.Descriptor(
  name='MitmproxyStartResponse',
  full_name='mitm.MitmproxyStartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mitmproxyId', full_name='mitm.MitmproxyStartResponse.mitmproxyId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=235,
)


_MITMPROXYSTOPREQUEST = _descriptor.Descriptor(
  name='MitmproxyStopRequest',
  full_name='mitm.MitmproxyStopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mitmproxyId', full_name='mitm.MitmproxyStopRequest.mitmproxyId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=280,
)


_MITMHEADER = _descriptor.Descriptor(
  name='MitmHeader',
  full_name='mitm.MitmHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mitm.MitmHeader.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mitm.MitmHeader.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=323,
)


_MITMREQUEST = _descriptor.Descriptor(
  name='MitmRequest',
  full_name='mitm.MitmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='mitm.MitmRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='mitm.MitmRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='mitm.MitmRequest.headers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='mitm.MitmRequest.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mitmproxyId', full_name='mitm.MitmRequest.mitmproxyId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=440,
)


_MITMRESPONSE = _descriptor.Descriptor(
  name='MitmResponse',
  full_name='mitm.MitmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='mitm.MitmResponse.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='mitm.MitmResponse.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='mitm.MitmResponse.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='mitm.MitmResponse.statusCode', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mitmproxyId', full_name='mitm.MitmResponse.mitmproxyId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=586,
)

_MITMREQUEST.fields_by_name['headers'].message_type = _MITMHEADER
_MITMRESPONSE.fields_by_name['request'].message_type = _MITMREQUEST
_MITMRESPONSE.fields_by_name['headers'].message_type = _MITMHEADER
DESCRIPTOR.message_types_by_name['VoidResponse'] = _VOIDRESPONSE
DESCRIPTOR.message_types_by_name['MitmproxyStartRequest'] = _MITMPROXYSTARTREQUEST
DESCRIPTOR.message_types_by_name['MitmproxyStartResponse'] = _MITMPROXYSTARTRESPONSE
DESCRIPTOR.message_types_by_name['MitmproxyStopRequest'] = _MITMPROXYSTOPREQUEST
DESCRIPTOR.message_types_by_name['MitmHeader'] = _MITMHEADER
DESCRIPTOR.message_types_by_name['MitmRequest'] = _MITMREQUEST
DESCRIPTOR.message_types_by_name['MitmResponse'] = _MITMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoidResponse = _reflection.GeneratedProtocolMessageType('VoidResponse', (_message.Message,), {
  'DESCRIPTOR' : _VOIDRESPONSE,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.VoidResponse)
  })
_sym_db.RegisterMessage(VoidResponse)

MitmproxyStartRequest = _reflection.GeneratedProtocolMessageType('MitmproxyStartRequest', (_message.Message,), {
  'DESCRIPTOR' : _MITMPROXYSTARTREQUEST,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.MitmproxyStartRequest)
  })
_sym_db.RegisterMessage(MitmproxyStartRequest)

MitmproxyStartResponse = _reflection.GeneratedProtocolMessageType('MitmproxyStartResponse', (_message.Message,), {
  'DESCRIPTOR' : _MITMPROXYSTARTRESPONSE,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.MitmproxyStartResponse)
  })
_sym_db.RegisterMessage(MitmproxyStartResponse)

MitmproxyStopRequest = _reflection.GeneratedProtocolMessageType('MitmproxyStopRequest', (_message.Message,), {
  'DESCRIPTOR' : _MITMPROXYSTOPREQUEST,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.MitmproxyStopRequest)
  })
_sym_db.RegisterMessage(MitmproxyStopRequest)

MitmHeader = _reflection.GeneratedProtocolMessageType('MitmHeader', (_message.Message,), {
  'DESCRIPTOR' : _MITMHEADER,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.MitmHeader)
  })
_sym_db.RegisterMessage(MitmHeader)

MitmRequest = _reflection.GeneratedProtocolMessageType('MitmRequest', (_message.Message,), {
  'DESCRIPTOR' : _MITMREQUEST,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.MitmRequest)
  })
_sym_db.RegisterMessage(MitmRequest)

MitmResponse = _reflection.GeneratedProtocolMessageType('MitmResponse', (_message.Message,), {
  'DESCRIPTOR' : _MITMRESPONSE,
  '__module__' : 'mitm_hub_pb2'
  # @@protoc_insertion_point(class_scope:mitm.MitmResponse)
  })
_sym_db.RegisterMessage(MitmResponse)



_MITMPROXYHUBSERVER = _descriptor.ServiceDescriptor(
  name='MitmProxyHubServer',
  full_name='mitm.MitmProxyHubServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=589,
  serialized_end=737,
  methods=[
  _descriptor.MethodDescriptor(
    name='start',
    full_name='mitm.MitmProxyHubServer.start',
    index=0,
    containing_service=None,
    input_type=_MITMPROXYSTARTREQUEST,
    output_type=_MITMPROXYSTARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stop',
    full_name='mitm.MitmProxyHubServer.stop',
    index=1,
    containing_service=None,
    input_type=_MITMPROXYSTOPREQUEST,
    output_type=_VOIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MITMPROXYHUBSERVER)

DESCRIPTOR.services_by_name['MitmProxyHubServer'] = _MITMPROXYHUBSERVER


_MITMPROXYHUBCLIENTSERVER = _descriptor.ServiceDescriptor(
  name='MitmProxyHubClientServer',
  full_name='mitm.MitmProxyHubClientServer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=740,
  serialized_end=883,
  methods=[
  _descriptor.MethodDescriptor(
    name='onMitmRequest',
    full_name='mitm.MitmProxyHubClientServer.onMitmRequest',
    index=0,
    containing_service=None,
    input_type=_MITMREQUEST,
    output_type=_MITMREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='onMitmResponse',
    full_name='mitm.MitmProxyHubClientServer.onMitmResponse',
    index=1,
    containing_service=None,
    input_type=_MITMRESPONSE,
    output_type=_MITMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MITMPROXYHUBCLIENTSERVER)

DESCRIPTOR.services_by_name['MitmProxyHubClientServer'] = _MITMPROXYHUBCLIENTSERVER

# @@protoc_insertion_point(module_scope)
